name: casso
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  flutter_svg: ^1.0.1
  dartz: ^0.10.1
  freezed_annotation: ^2.0.3
  firebase_auth: ^3.3.18
  firebase_core: ^1.17.0
  google_sign_in: ^5.3.1
  injectable: ^1.5.3
  get_it: ^7.2.0
  cloud_firestore: ^3.1.16
  json_serializable: ^6.2.0
  get_storage: ^2.0.3
  json_annotation: ^4.5.0
  # auto_route: ^4.0.1

dev_dependencies:
  freezed: ^2.0.3+1
  build_runner: ^2.1.10
  injectable_generator: ^1.5.3
  # auto_route_generator: ^4.0.0

  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
  fonts: 
    - family: Ubuntu
      fonts: 
        - asset: assets/fonts/Ubuntu-Regular.ttf
        - asset: assets/fonts/Ubuntu-Light.ttf
          weight: 500
        - asset: assets/fonts/Ubuntu-Medium.ttf
          weight: 600
        - asset: assets/fonts/Ubuntu-Bold.ttf
          weight: 700
 
